# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"display_all": "01_extend_pandas.ipynb",
         "evaluate_join": "01_extend_pandas.ipynb",
         "mem_usage": "01_extend_pandas.ipynb",
         "optimize_dataframe_memory_usage": "01_extend_pandas.ipynb",
         "zero_pad": "01_extend_pandas.ipynb"}

modules = ["extend_pandas.py"]

doc_url = "https://ryanfras.github.io/datofi/"

git_url = "https://github.com/ryanfras/datofi/tree/0/"

def custom_doc_links(name): return None
