# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://ryanfras.github.io/datofi/"

git_url = "https://github.com/ryanfras/datofi/tree/0/"

def custom_doc_links(name): return None
